easy_admin:
    entities:
        # List the entity class name you want to manage
        Product:
            class: App\Entity\Product
            list:
                fields:
                    - id
                    - name
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
                    - description
                    - categories
            form:
                fields:
                    - { property: 'name', label: 'Name' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'categories', label: 'Categories', type: 'entity', type_options: { class: 'App\Entity\Category', multiple: true } }
                    - { property: 'price', label: 'Price' }

        Category:
            class: App\Entity\Category
        User:
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'USER': 'ROLE_USER', 'ADMIN': 'ROLE_ADMIN' } } }
        Article:
            class: App\Entity\Article
        Tag:
            class: App\Entity\Tag
        Image:
            class: App\Entity\Image
