easy_admin:
    entities:
        # List the entity class name you want to manage
        Product:
            class: App\Entity\Product
            form:
                fields:
                    - { property: 'name', label: 'Name' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'categories', label: 'Categories', type: 'entity', type_options: { class: 'App\Entity\Category', multiple: true } }
                    - { property: 'price', label: 'Price' }

        Category:
            class: App\Entity\Category
        User:
            class: App\Entity\User
        Article:
            class: App\Entity\Article
        Tag:
            class: App\Entity\Tag
        Image:
            class: App\Entity\Image
