easy_admin:
    entities:
        # List the entity class name you want to manage
        Product:
            class: App\Entity\Product
            form:
                fields:
                    - { property: 'categories', label: 'Categories', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Category' } }
        Category:
            class: App\Entity\Category
        User:
            class: App\Entity\User
