runtime: php
env: flex
runtime_config:
  document_root: public
env_variables:
  APP_ENV: "prod"
  APP_SECRET: "bla-bla-bla"
  MYSQL_USER: root
  MYSQL_PASSWORD: hello-cloud
  MYSQL_DSN: mysql:dbname=hello-google-cloud;unix_socket=/cloudsql/opportune-geode-204614:asia-southeast1:hello-google-cloud
beta_settings:
  # for Cloud SQL, set this value to the Cloud SQL connection name,
  # e.g. "project:region:cloudsql-instance"
  cloud_sql_instances: "opportune-geode-204614:asia-southeast1:hello-google-cloud"