runtime: php
env: flex

runtime_config:
  document_root: public

env_variables:
  APP_ENV: "prod"
  APP_SECRET: "bla-bla-bla"
  APP_DEBUG: true
  ## Set these environment variables according to your CloudSQL configuration.
  #DATABASE_URL: "mysql://root:hello-cloud@unix_socket=/cloudsql/opportune-geode-204614:asia-southeast1:hello-google-cloud/hello-google-cloud"
  DB_DATABASE: hello-google-cloud
  DB_USERNAME: root
  DB_PASSWORD: hello-cloud
  DB_SOCKET: '/cloudsql/opportune-geode-204614:asia-southeast1:hello-google-cloud'
  MYSQL_DSN: 'mysql:unix_socket=/cloudsql/opportune-geode-204614:asia-southeast1:hello-google-cloud;dbname=hello-google-cloud'
  # cloud storage
  UPLOAD_ROOT: 'gs://opportune-geode-204614.appspot.com/public/uploads/images'

beta_settings:
  # for Cloud SQL, set this value to the Cloud SQL connection name,
  # e.g. "project:region:cloudsql-instance"
  cloud_sql_instances: 'opportune-geode-204614:asia-southeast1:hello-google-cloud'