index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin